trigger:
- master

pool: MyAgent

variables:
  solution: 'library/*.*proj'
  buildPlatform: 'AnyCPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@0

- task: NuGetCommand@2
  inputs:
    restoreSolution: 'library/*.config'
    restoreDirectory: '../packages'

- task: MSBuild@1
  inputs:
    solution: $(solution)
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'