trigger:
- master

pool: MyAgent

# todo: use variables to assign value
variables:
  solution: 'library/*.*proj'
  buildPlatform: 'AnyCPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@0

- task: NuGetCommand@2
  inputs:
    restoreSolution: 'library\*.config'
    restoreDirectory: '..\packages'

- task: MSBuild@1
  inputs:
    solution: $(solution)
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: CopyFiles@2
  inputs:
    Contents: |
      **\bin\**
      nuget\**\*.nuspec
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    flattenFolders: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'package'