trigger:
- master

pool: MyAgent

steps:
- task: NuGetToolInstaller@0

- task: NuGetCommand@2
  inputs:
    restoreSolution: 'library\*.config'
    restoreDirectory: '..\packages'

- task: MSBuild@1
  inputs:
    solution: 'library/*.*proj'
    platform: 'AnyCPU'
    configuration: 'Release'

- task: CopyFiles@2
  displayName: 'Copy packages to artifacts staging directory' 
  inputs:
    Contents: '**\bin\**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)\lib\.NetFramework 4.0'
    flattenFolders: true

- task: CopyFiles@2
  displayName: 'Copy nuspec to artifacts staging directory' 
  inputs:
    Contents: 'nuget\**\*.nuspec'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    flattenFolders: true

- task: PublishBuildArtifacts@1
  displayName: 'Publish artifacts'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'harta-recaptcha'