trigger:
- master

pool: MyAgent

steps:
- task: NuGetToolInstaller@0

- task: NuGetCommand@2
  inputs:
    restoreSolution: 'library/*.config'
    restoreDirectory: 'nuget/recaptcha/lib/.NetFramework 4.0/'

- task: MSBuild@1
  inputs:
    solution: 'library/*.*proj'
    platform: 'AnyCPU'
    configuration: 'Release'