trigger:
- master

pool: MyAgent

variables:
  solution: 'library/*.*proj'
  buildPlatform: 'AnyCPU'
  buildConfiguration: 'Release'

steps:
- task: MSBuild@1
  inputs:
    solution: $(solution)
    platform: $(buildPlatform)
    msbuildArguments: $(buildConfiguration)
    restoreNugetPackages: true